name: Publish

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'  # 自动缓存pnpm，加速后续安装

      # 关键：显式安装pnpm（解决找不到命令问题）
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf \
            build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev

      - name: Install dependencies (macos)
        if: matrix.os == 'macos-latest'
        run: |
          brew install webkit2gtk

      - name: Install dependencies (windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install webkit2gtk

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build
        run: pnpm tauri build

      - name: Upload artifacts (ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/manhuagui-downloader

      - name: Upload artifacts (windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/manhuagui-downloader.exe

      - name: Upload artifacts (macos)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/manhuagui-downloader

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/manhuagui-downloader
            src-tauri/target/release/manhuagui-downloader.exe
