name: Publish
on:
  push:
    tags: ['v*']
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # 关键：固定 Node.js 版本，确保环境一致
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 强制安装 pnpm 到全局，并显式添加路径到 PATH
      - name: Install & Link pnpm
        run: |
          npm install -g pnpm
          echo "$(npm root -g)/pnpm" >> $GITHUB_PATH  # Linux/macOS
          echo "%APPDATA%\npm" >> $GITHUB_PATH       # Windows（自动适配）

      # 安装 Rust（Tauri 必用）
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      # Ubuntu 依赖（适配 Debian）
      - name: Install Ubuntu Dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf \
            build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev

      # macOS 依赖
      - name: Install macOS Dependencies
        if: matrix.os == 'macos-latest'
        run: brew install webkit2gtk

      # Windows 依赖
      - name: Install Windows Dependencies
        if: matrix.os == 'windows-latest'
        run: choco install webkit2gtk

      # 安装前端依赖（必须用 pnpm）
      - name: Install Frontend Dependencies
        run: pnpm install

      # 构建项目（Tauri 编译）
      - name: Build Project
        run: pnpm tauri build

      # 上传 Debian 可用的 .deb 包
      - name: Upload Ubuntu Artifacts
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/manhuagui-downloader

      # 上传其他系统产物（可选，不影响 Debian 编译）
      - name: Upload Windows Artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/manhuagui-downloader.exe

      - name: Upload macOS Artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/manhuagui-downloader

      # 发布到 GitHub Releases
      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/manhuagui-downloader
            src-tauri/target/release/manhuagui-downloader.exe
